# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Domen R.
tagline:          'card'
description:      'Deep Learning & Computer Vision Engineer with R&D background in Applied Research'
#url:              /
baseurl:          /

author:
  name:           'Domen R.'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
linkedin:
  url:           https://www.linkedin.com/in/domenracki
gscholar:
  url:           https://scholar.google.com/citations?user=SeDLjRMAAAAJ&hl=sl&oi=ao
github:
  url:           https://github.com/donrax
