# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Domen Rački, PhD
tagline:          'card'
description:      'Applied AI/ML Engineer'
#url:              /
baseurl:          /

author:
  name:           'Domen Rački, PhD'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
linkedin:
  url:           https://www.linkedin.com/in/domenracki
gscholar:
  url:           https://scholar.google.com/citations?user=SeDLjRMAAAAJ&hl=sl&oi=ao
github:
  url:           https://github.com/donrax
